// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_GeneralSettingsScreen_screen_init(void)
{
ui_GeneralSettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_GeneralSettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GeneralSettingsScreen, lv_color_hex(0x28652A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GeneralSettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_GeneralSettingsScreen);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, -80 );
lv_obj_set_y( ui_Label23, -105 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"Settings");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_GeneralSettingsScreen);
lv_obj_set_width( ui_Panel12, 456);
lv_obj_set_height( ui_Panel12, 100);
lv_obj_set_x( ui_Panel12, -1 );
lv_obj_set_y( ui_Panel12, 88 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, -138 );
lv_obj_set_y( ui_Label24, -28 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Screen Brightness:");
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenBrightnessSlider = lv_slider_create(ui_Panel12);
lv_slider_set_range(ui_ScreenBrightnessSlider, 1,100);
lv_slider_set_value( ui_ScreenBrightnessSlider, 80, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_ScreenBrightnessSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_ScreenBrightnessSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_ScreenBrightnessSlider, 400);
lv_obj_set_height( ui_ScreenBrightnessSlider, 30);
lv_obj_set_x( ui_ScreenBrightnessSlider, 0 );
lv_obj_set_y( ui_ScreenBrightnessSlider, 18 );
lv_obj_set_align( ui_ScreenBrightnessSlider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ScreenBrightnessSlider, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenBrightnessSlider, lv_color_hex(0xFAFF82), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenBrightnessSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenBrightnessLabel = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_ScreenBrightnessLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ScreenBrightnessLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ScreenBrightnessLabel, -30 );
lv_obj_set_y( ui_ScreenBrightnessLabel, -28 );
lv_obj_set_align( ui_ScreenBrightnessLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ScreenBrightnessLabel,"80%");

ui_Panel18 = lv_obj_create(ui_GeneralSettingsScreen);
lv_obj_set_width( ui_Panel18, 188);
lv_obj_set_height( ui_Panel18, 54);
lv_obj_set_x( ui_Panel18, -133 );
lv_obj_set_y( ui_Panel18, -2 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel18, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch4 = lv_switch_create(ui_Panel18);
lv_obj_set_width( ui_Switch4, 50);
lv_obj_set_height( ui_Switch4, 25);
lv_obj_set_x( ui_Switch4, -58 );
lv_obj_set_y( ui_Switch4, 1 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_CENTER );

ui_Image20 = lv_img_create(ui_GeneralSettingsScreen);
lv_img_set_src(ui_Image20, &ui_img_tomato_png);
lv_obj_set_width( ui_Image20, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image20, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_Image20, -185 );
lv_obj_set_y( ui_Image20, -108 );
lv_obj_set_align( ui_Image20, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image20, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image20, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown2 = lv_dropdown_create(ui_GeneralSettingsScreen);
lv_obj_set_width( ui_Dropdown2, 150);
lv_obj_set_height( ui_Dropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown2, 113 );
lv_obj_set_y( ui_Dropdown2, -1 );
lv_obj_set_align( ui_Dropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

lv_obj_add_event_cb(ui_ScreenBrightnessSlider, ui_event_ScreenBrightnessSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_GeneralSettingsScreen, ui_event_GeneralSettingsScreen, LV_EVENT_ALL, NULL);

}
