// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_LightDurationScreen_screen_init(void)
{
ui_LightDurationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LightDurationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LightDurationScreen, lv_color_hex(0x28652A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightDurationScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LightDurationScreen, lv_color_hex(0x0A002D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_LightDurationScreen, 110, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_LightDurationScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_LightDurationScreen, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_LightDurationScreen);
lv_obj_set_width( ui_Panel8, 745);
lv_obj_set_height( ui_Panel8, 174);
lv_obj_set_x( ui_Panel8, 0 );
lv_obj_set_y( ui_Panel8, -139 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_LightDurationSlider = lv_slider_create(ui_Panel8);
lv_slider_set_range(ui_LightDurationSlider, 0,48);
lv_slider_set_value( ui_LightDurationSlider, 20, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LightDurationSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LightDurationSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LightDurationSlider, 400);
lv_obj_set_height( ui_LightDurationSlider, 30);
lv_obj_set_x( ui_LightDurationSlider, -18 );
lv_obj_set_y( ui_LightDurationSlider, -24 );
lv_obj_set_align( ui_LightDurationSlider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LightDurationSlider, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LightDurationSlider, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_radius(ui_LightDurationSlider, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightDurationSlider, lv_color_hex(0x17006B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightDurationSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LightDurationSlider, lv_color_hex(0xECECEC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LightDurationSlider, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LightDurationSlider, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_LightDurationSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LightDurationSlider, lv_color_hex(0xF6CF06), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightDurationSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LightDurationSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightDurationSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_LightDurationSlider, &ui_img_303216376, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_LightDurationSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_NowSlider = lv_slider_create(ui_Panel8);
lv_slider_set_range(ui_NowSlider, 0,48);
lv_slider_set_value( ui_NowSlider, 20, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_NowSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_NowSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_NowSlider, 400);
lv_obj_set_height( ui_NowSlider, 30);
lv_obj_set_x( ui_NowSlider, -16 );
lv_obj_set_y( ui_NowSlider, 41 );
lv_obj_set_align( ui_NowSlider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NowSlider, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_NowSlider, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_NowSlider, lv_color_hex(0xE8FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NowSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_NowSlider, lv_color_hex(0xE8FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NowSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_NowSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NowSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_NowSlider, &ui_img_now_arrow_2_png, LV_PART_KNOB | LV_STATE_DEFAULT );

ui_Image8 = lv_img_create(ui_Panel8);
lv_img_set_src(ui_Image8, &ui_img_791711567);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 128
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 128
lv_obj_set_x( ui_Image8, -295 );
lv_obj_set_y( ui_Image8, 1 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Panel8);
lv_img_set_src(ui_Image9, &ui_img_432815713);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 128
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 128
lv_obj_set_x( ui_Image9, 273 );
lv_obj_set_y( ui_Image9, -3 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LightDurationLightLabel = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_LightDurationLightLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightDurationLightLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightDurationLightLabel, -295 );
lv_obj_set_y( ui_LightDurationLightLabel, 1 );
lv_obj_set_align( ui_LightDurationLightLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightDurationLightLabel,"12h");
lv_obj_set_style_text_color(ui_LightDurationLightLabel, lv_color_hex(0x636A01), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightDurationLightLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LightDurationLightLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightDurationLightLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LightDurationDarkLabel = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_LightDurationDarkLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LightDurationDarkLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LightDurationDarkLabel, 269 );
lv_obj_set_y( ui_LightDurationDarkLabel, 40 );
lv_obj_set_align( ui_LightDurationDarkLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LightDurationDarkLabel,"12h");
lv_obj_set_style_text_color(ui_LightDurationDarkLabel, lv_color_hex(0x1608B1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LightDurationDarkLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LightDurationDarkLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_LightDurationScreen);
lv_obj_set_width( ui_Panel6, 611);
lv_obj_set_height( ui_Panel6, 107);
lv_obj_set_x( ui_Panel6, -61 );
lv_obj_set_y( ui_Panel6, 26 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LEDBrightnessSlider = lv_slider_create(ui_Panel6);
lv_slider_set_range(ui_LEDBrightnessSlider, 10,100);
lv_slider_set_value( ui_LEDBrightnessSlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LEDBrightnessSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LEDBrightnessSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LEDBrightnessSlider, 400);
lv_obj_set_height( ui_LEDBrightnessSlider, 30);
lv_obj_set_x( ui_LEDBrightnessSlider, 50 );
lv_obj_set_y( ui_LEDBrightnessSlider, 0 );
lv_obj_set_align( ui_LEDBrightnessSlider, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LEDBrightnessSlider, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LEDBrightnessSlider, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_radius(ui_LEDBrightnessSlider, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LEDBrightnessSlider, lv_color_hex(0xEBEB18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LEDBrightnessSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_LEDBrightnessSlider, LV_GRAD_DIR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LEDBrightnessSlider, lv_color_hex(0xFFFE2B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LEDBrightnessSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LEDBrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LEDBrightnessSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_LEDBrightnessSlider, &ui_img_303216376, LV_PART_KNOB | LV_STATE_DEFAULT );

ui_Image4 = lv_img_create(ui_Panel6);
lv_img_set_src(ui_Image4, &ui_img_1756057095);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_Image4, -244 );
lv_obj_set_y( ui_Image4, 12 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LEDBrightnessLabel = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_LEDBrightnessLabel, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_LEDBrightnessLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LEDBrightnessLabel, 25 );
lv_obj_set_y( ui_LEDBrightnessLabel, -36 );
lv_obj_set_align( ui_LEDBrightnessLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LEDBrightnessLabel,"10%");
lv_obj_set_style_text_font(ui_LEDBrightnessLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_LightDurationScreen);
lv_obj_set_width( ui_Panel10, 236);
lv_obj_set_height( ui_Panel10, 100);
lv_obj_set_x( ui_Panel10, 126 );
lv_obj_set_y( ui_Panel10, 151 );
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Image15 = lv_img_create(ui_Panel10);
lv_img_set_src(ui_Image15, &ui_img_harvest_png);
lv_obj_set_width( ui_Image15, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image15, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_Image15, -77 );
lv_obj_set_y( ui_Image15, 1 );
lv_obj_set_align( ui_Image15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_btn_create(ui_Panel10);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 31 );
lv_obj_set_y( ui_Button1, 1 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFE7B0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"Harvest");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_LightDurationScreen);
lv_obj_set_width( ui_Panel4, 298);
lv_obj_set_height( ui_Panel4, 100);
lv_obj_set_x( ui_Panel4, -216 );
lv_obj_set_y( ui_Panel4, 153 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DayDownButton = lv_imgbtn_create(ui_Panel4);
lv_imgbtn_set_src(ui_DayDownButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1749885216, NULL);
lv_imgbtn_set_src(ui_DayDownButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1749885216, NULL);
lv_obj_set_height( ui_DayDownButton, 64);
lv_obj_set_width( ui_DayDownButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_DayDownButton, 104 );
lv_obj_set_y( ui_DayDownButton, -2 );
lv_obj_set_align( ui_DayDownButton, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_DayDownButton, lv_color_hex(0x242424), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_DayDownButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_DayUpButton = lv_imgbtn_create(ui_Panel4);
lv_imgbtn_set_src(ui_DayUpButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2060199463, NULL);
lv_obj_set_height( ui_DayUpButton, 64);
lv_obj_set_width( ui_DayUpButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_DayUpButton, -106 );
lv_obj_set_y( ui_DayUpButton, 0 );
lv_obj_set_align( ui_DayUpButton, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_DayUpButton, lv_color_hex(0x242424), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_DayUpButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_DayCounterLabel = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_DayCounterLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DayCounterLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DayCounterLabel, 35 );
lv_obj_set_y( ui_DayCounterLabel, -2 );
lv_obj_set_align( ui_DayCounterLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DayCounterLabel,"0");
lv_obj_set_style_text_font(ui_DayCounterLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DayCounterLabel, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DayCounterLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DayCounterLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DayCounterLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DayCounterLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DayCounterLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DayCounterLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalendarImage = lv_img_create(ui_Panel4);
lv_img_set_src(ui_CalendarImage, &ui_img_appointment_png);
lv_obj_set_width( ui_CalendarImage, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_CalendarImage, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_CalendarImage, -29 );
lv_obj_set_y( ui_CalendarImage, -5 );
lv_obj_set_align( ui_CalendarImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalendarImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CalendarImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LightDurationSlider, ui_event_LightDurationSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_NowSlider, ui_event_NowSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LEDBrightnessSlider, ui_event_LEDBrightnessSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DayDownButton, ui_event_DayDownButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DayUpButton, ui_event_DayUpButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LightDurationScreen, ui_event_LightDurationScreen, LV_EVENT_ALL, NULL);

}
