// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_LaunchScreen_screen_init(void)
{
ui_LaunchScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LaunchScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LaunchScreen, lv_color_hex(0x28652A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LaunchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_LaunchScreen);
lv_img_set_src(ui_Image1, &ui_img_tomato_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -1 );
lv_obj_set_y( ui_Image1, -73 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StartNewGrow = lv_btn_create(ui_LaunchScreen);
lv_obj_set_width( ui_StartNewGrow, 200);
lv_obj_set_height( ui_StartNewGrow, 50);
lv_obj_set_x( ui_StartNewGrow, 0 );
lv_obj_set_y( ui_StartNewGrow, 8 );
lv_obj_set_align( ui_StartNewGrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StartNewGrow, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StartNewGrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_StartNewGrow);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Start new Grow");

ui_DryAHarverst = lv_btn_create(ui_LaunchScreen);
lv_obj_set_width( ui_DryAHarverst, 200);
lv_obj_set_height( ui_DryAHarverst, 50);
lv_obj_set_x( ui_DryAHarverst, 0 );
lv_obj_set_y( ui_DryAHarverst, 74 );
lv_obj_set_align( ui_DryAHarverst, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DryAHarverst, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DryAHarverst, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_DryAHarverst);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Dry a Harvest");

}
