// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_SensorSettingsScreen_screen_init(void)
{
ui_SensorSettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SensorSettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorSettingsScreen, lv_color_hex(0x28652A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorSettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_Panel7, 215);
lv_obj_set_height( ui_Panel7, 96);
lv_obj_set_x( ui_Panel7, -119 );
lv_obj_set_y( ui_Panel7, -20 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label34 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, 0 );
lv_obj_set_y( ui_Label34, -27 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"Elevation above Sea in\nmeters");
lv_obj_set_style_text_align(ui_Label34, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_Panel9, 215);
lv_obj_set_height( ui_Panel9, 96);
lv_obj_set_x( ui_Panel9, 116 );
lv_obj_set_y( ui_Panel9, -20 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label37 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, 0 );
lv_obj_set_y( ui_Label37, -33 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"Temperature Offset");
lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, 0 );
lv_obj_set_y( ui_Label15, -119 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Sensor Settings");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorSettingsSaveButton = lv_btn_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_SensorSettingsSaveButton, 278);
lv_obj_set_height( ui_SensorSettingsSaveButton, 50);
lv_obj_set_x( ui_SensorSettingsSaveButton, 0 );
lv_obj_set_y( ui_SensorSettingsSaveButton, 79 );
lv_obj_set_align( ui_SensorSettingsSaveButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SensorSettingsSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SensorSettingsSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label33 = lv_label_create(ui_SensorSettingsSaveButton);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"SAVE SENSOR SETTINGS");
lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorSettingsInfoLabel = lv_label_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_SensorSettingsInfoLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorSettingsInfoLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SensorSettingsInfoLabel, 0 );
lv_obj_set_y( ui_SensorSettingsInfoLabel, 129 );
lv_obj_set_align( ui_SensorSettingsInfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorSettingsInfoLabel,"");
lv_obj_set_style_text_align(ui_SensorSettingsInfoLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SensorSettingsSaveButton, ui_event_SensorSettingsSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SensorSettingsScreen, ui_event_SensorSettingsScreen, LV_EVENT_ALL, NULL);

}
