// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_SensorSettingsScreen_screen_init(void)
{
ui_SensorSettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SensorSettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorSettingsScreen, lv_color_hex(0x28652A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorSettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, 0 );
lv_obj_set_y( ui_Label15, -119 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Air Devices");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorSettingsSaveButton = lv_btn_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_SensorSettingsSaveButton, 278);
lv_obj_set_height( ui_SensorSettingsSaveButton, 50);
lv_obj_set_x( ui_SensorSettingsSaveButton, 2 );
lv_obj_set_y( ui_SensorSettingsSaveButton, 114 );
lv_obj_set_align( ui_SensorSettingsSaveButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SensorSettingsSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SensorSettingsSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label33 = lv_label_create(ui_SensorSettingsSaveButton);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"Toggle");
lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorSettingsInfoLabel = lv_label_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_SensorSettingsInfoLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorSettingsInfoLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SensorSettingsInfoLabel, 0 );
lv_obj_set_y( ui_SensorSettingsInfoLabel, 129 );
lv_obj_set_align( ui_SensorSettingsInfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorSettingsInfoLabel,"");
lv_obj_set_style_text_align(ui_SensorSettingsInfoLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_SensorSettingsScreen);
lv_obj_set_width( ui_Panel7, 437);
lv_obj_set_height( ui_Panel7, 50);
lv_obj_set_x( ui_Panel7, -1 );
lv_obj_set_y( ui_Panel7, -42 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image24 = lv_img_create(ui_Panel7);
lv_img_set_src(ui_Image24, &ui_img_1319116584);
lv_obj_set_width( ui_Image24, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_Image24, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_Image24, -183 );
lv_obj_set_y( ui_Image24, 0 );
lv_obj_set_align( ui_Image24, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image24, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image24, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image24, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label34 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, -112 );
lv_obj_set_y( ui_Label34, 1 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"Socket");
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button2, 127);
lv_obj_set_height( ui_Button2, 30);
lv_obj_set_x( ui_Button2, 9 );
lv_obj_set_y( ui_Button2, 0 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x70C92E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Button2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Button2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label35 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label35, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label35, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label35, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label35,"Pair");
lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Panel7);
lv_obj_set_width( ui_Button3, 127);
lv_obj_set_height( ui_Button3, 30);
lv_obj_set_x( ui_Button3, 146 );
lv_obj_set_y( ui_Button3, 0 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x9E2EC9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Button3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Button3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"Leave");
lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SensorSettingsSaveButton, ui_event_SensorSettingsSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SensorSettingsScreen, ui_event_SensorSettingsScreen, LV_EVENT_ALL, NULL);

}
