// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: TT

#include "../ui.h"

void ui_ZigbeeScreen_screen_init(void)
{
ui_ZigbeeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ZigbeeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ZigbeeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ZigbeeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ZigbeeScreen, ui_event_ZigbeeScreen, LV_EVENT_ALL, NULL);

}
