// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TT

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void play_intro(lv_event_t * e);
void init_tomatotent(lv_event_t * e);
void save_light_duration_screen(lv_event_t * e);
void light_duration_slider(lv_event_t * e);
void now_slider(lv_event_t * e);
void save_led_brightness_screen(lv_event_t * e);
void LEDBrightnessSlider(lv_event_t * e);
void decrease_day_counter(lv_event_t * e);
void increase_day_counter(lv_event_t * e);
void save_screen_brightness_screen(lv_event_t * e);
void screen_brightness_slider(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
