// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TT

#include "lvgl.h"
#include "ui_events.h"
#include "ui.h"
#include <math.h>  
#include "esp_log.h"
#include <stdio.h>

static const char *TAG = "ui_events.c";

//static char str[12];

//SplashScreen

#ifndef PI
#define PI  (3.14159f)
#endif

typedef struct {
    lv_obj_t *scr;
    int count_val;
} my_timer_context_t;

my_timer_context_t my_tim_ctx;
lv_obj_t *arc[3];
lv_obj_t *img_text = NULL;
lv_color_t arc_color[] = {
    LV_COLOR_MAKE(0, 116, 0),
    LV_COLOR_MAKE(0, 162, 0),
    LV_COLOR_MAKE(0, 228, 0),
};

// LVGL image declare
LV_IMG_DECLARE(ui_img_tomato_png)
LV_IMG_DECLARE(tomatotent_text)

void anim_timer_cb(lv_timer_t *timer)
{
    my_timer_context_t *timer_ctx = (my_timer_context_t *) timer->user_data;
    int count = timer_ctx->count_val;
    lv_obj_t *scr = timer_ctx->scr;

    // Play arc animation
    if (count < 90) {
        lv_coord_t arc_start = count > 0 ? (1 - cosf(count / 180.0f * PI)) * 270 : 0;
        lv_coord_t arc_len = (sinf(count / 180.0f * PI) + 1) * 135;

        for (size_t i = 0; i < sizeof(arc) / sizeof(arc[0]); i++) {
            lv_arc_set_bg_angles(arc[i], arc_start, arc_len);
            lv_arc_set_rotation(arc[i], (count + 120 * (i + 1)) % 360);
        }
    }

    // Delete arcs when animation finished
    if (count == 90) {
        for (size_t i = 0; i < sizeof(arc) / sizeof(arc[0]); i++) {
            lv_obj_del(arc[i]);
        }

        // Create new image and make it transparent
        img_text = lv_img_create(scr);
        lv_img_set_src(img_text, &tomatotent_text);
        lv_obj_set_style_img_opa(img_text, 0, 0);
    }

    // Move images when arc animation finished
    if ((count >= 100) && (count <= 180)) {
        lv_coord_t offset = (sinf((count - 140) * 2.25f / 90.0f) + 1) * 20.0f;
        lv_obj_align(img_text, LV_ALIGN_CENTER, 0, -2.8 * offset);
        lv_obj_set_style_img_opa(img_text, offset / 40.0f * 255, 0);
    }

    // Delete timer when all animation finished
    if ((count += 5) == 220) {
        lv_timer_del(timer);
        
    } else {
        timer_ctx->count_val = count;
    }
}

void start_animation(lv_obj_t *scr)
{

    // Create arcs
    for (size_t i = 0; i < sizeof(arc) / sizeof(arc[0]); i++) {
        arc[i] = lv_arc_create(scr);

        // Set arc caption
        lv_obj_set_size(arc[i], 220 - 30 * i, 220 - 30 * i);
        lv_arc_set_bg_angles(arc[i], 120 * i, 10 + 120 * i);
        lv_arc_set_value(arc[i], 0);

        // Set arc style
        lv_obj_remove_style(arc[i], NULL, LV_PART_KNOB);
        lv_obj_set_style_arc_width(arc[i], 10, 0);
        lv_obj_set_style_arc_color(arc[i], arc_color[i], 0);

        // Make arc center
        lv_obj_center(arc[i]);
    }

    if (img_text) {
        lv_obj_del(img_text);
        img_text = NULL;
    }

    // Create timer for animation
    my_tim_ctx.count_val = -200;
    my_tim_ctx.scr = scr;
    lv_timer_create(anim_timer_cb, 20, &my_tim_ctx);

}

void play_intro(lv_event_t * e)
{
    start_animation(ui_SplashScreen);
}

/////////////////////////////////////
/////// LightDurationScreen /////////
/////////////////////////////////////

static int light_duration_slider_value;
static float_t light_duration;
static float dark_duration;

void light_duration_slider(lv_event_t * e) {
	
	lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
	light_duration_slider_value = lv_slider_get_value(target);
	
	light_duration = (float_t)light_duration_slider_value / 2;

	ESP_LOGI(TAG, "%.1f", light_duration);
	//fprintf(str, "%f", light_duration);
	
	//lv_label_set_text(ui_LightDurationLightLabel, );
}
